### ISSUE TITLE
Trouble Loading Pretrained Weights

### ISSUE THREAD

**Issue by jafri1272** [PIC4SeR/EdgeSRGAN#2]
Hello,

I am currently attempting to use your Super Resolution GAN code from this repository. I'm trying to test the model with the provided pre-trained weights (edgesrgan.h5), but I'm encountering an issue while loading them into the model.

The error I receive is: "Layer count mismatch when loading weights from the file. Model expected 39 layers found 29 saved layers." I've tried all the configurations provided in the config file (tiny, small, base, and large) but the same issue persists.

I'm using the load_weights function with by_name=False and skip_mismatch=False arguments to load the weights. I've also attempted changing these parameters but without success.

Could you please provide some guidance on which model size or configuration corresponds with the provided weights? Or is there any additional step or consideration that I should be aware of when loading the weights?

Thank you for your assistance.

**Comment by cccgong** [comment]
I'm having the same issue here.  I guess we will need to train our own model from scratch.

However I'm having issues with that too, as there's no "pre_generator_small_ablation_3_batchnorm.h5" file

**Comment by simoneangarano** [comment]
> Hello,
> 
> I am currently attempting to use your Super Resolution GAN code from this repository. I'm trying to test the model with the provided pre-trained weights (edgesrgan.h5), but I'm encountering an issue while loading them into the model.
> 
> The error I receive is: "Layer count mismatch when loading weights from the file. Model expected 39 layers found 29 saved layers." I've tried all the configurations provided in the config file (tiny, small, base, and large) but the same issue persists.
> 
> I'm using the load_weights function with by_name=False and skip_mismatch=False arguments to load the weights. I've also attempted changing these parameters but without success.
> 
> Could you please provide some guidance on which model size or configuration corresponds with the provided weights? Or is there any additional step or consideration that I should be aware of when loading the weights?
> 
> Thank you for your assistance.

Hi, sorry for the late reply. I found the error. In the default config file, the small model activation is different from what was reported in the paper ("prelu" instead of "relu"). That's why the weights are not loading properly. This is due to some late tests for which the config file was modified. Please edit this value, and everything should work properly.
Thanks for the patience!

**Comment by simoneangarano** [comment]
> I'm having the same issue here. I guess we will need to train our own model from scratch.
> 
> However I'm having issues with that too, as there's no "pre_generator_small_ablation_3_batchnorm.h5" file

Of course, you can easily retrain the models from scratch quickly. 
Before training with the GAN optimization method, you must train with only PSNR as the objective (MODE=PSNR in config). Once you have trained the model, you can specify the corresponding weights for the GAN training (MODE=GAN in config).
I hope this helps solve your doubts!
