### ISSUE TITLE
which distillation method is better？

### ISSUE THREAD

**Issue by YilanWang** [PIC4SeR/EdgeSRGAN#3]

**Comment by YilanWang** [comment]
thanks for this great job! It helps me a lot! In your code, I found there are many kd methods can selected, like FAKD, BRKD, etc. In your experiments, which is better? thanks ~

**Comment by simoneangarano** [comment]
Hi! Thanks for your interest in our paper. Based on our experiments, FAKD works better here. However, we modified the original method to suit our methodology better (more info in the paper [Generative Adversarial Super-Resolution at the Edge with Knowledge Distillation](https://arxiv.org/abs/2209.03355), section 3.3).
I hope this helps!

**Comment by YilanWang** [comment]
very thanks for your reply! and I still have a little question, in fakd, even if the feat map size is [256x256], the size of affinity matrix is [1,1,65536,65536], and only batch size =1 (1 teacher feat and 1 student feat) will use almost 33 GiB memory! How to run the method correctly?

**Comment by simoneangarano** [comment]
Uhm, no, the affinity matrix should still be 256x256. Check our paper and the original FAKD paper (https://ieeexplore.ieee.org/document/9190917).
