### ISSUE TITLE
pre_generator_small_ablation_3_batchnorm.h5 not found

### ISSUE THREAD

**Issue by pontscho** [PIC4SeR/EdgeSRGAN#4]
Can you put this file into the repository or somewhere else ?

**Comment by simoneangarano** [comment]
Hi @pontscho 
Sorry for the late reply. I added ```pre_generator_small.h5``` to the shared folder at this [link](https://drive.google.com/drive/folders/1E21iZ2apadpS--zh8PHRCM4DVuIKdOOJ?usp=drive_link).
Hope this helps!
